@echo off
echo Cleaning build directory...
rmdir /s /q build
echo Generating CMake...
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -A x64
echo Building project...
cmake --build build --config Release
echo Starting app...
.\build\Release\CustomMixer.exe
